kind: pipeline
name: default

steps:
  - name: build and push image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 30 # give docker enough time to start
      - docker build -t mari-medical-web .
      - docker tag mari-medical-web:latest registry.mari.casa/mari-medical-web:latest
      - docker push registry.mari.casa/mari-medical-web:latest

  - name: deploy stack
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.1.100
      username: cfu288
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 30m
      script:
        - curl https://gitea.mari.casa/cfu288/mari-medical/raw/branch/main/docker-compose.yaml > docker-compose.prod.yaml
        - docker stack deploy -c docker-compose.prod.yaml mari-medical

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - main
