kind: pipeline
name: default
type: docker

clone:
  depth: 2

steps:
  # - name: app-check-if-changed
  #   image: node:16.14.0
  #   commands:
  #     - npm ci
  #     - npx nx print-affected --type=app --select=projects --base=HEAD~1
  #     - npx nx print-affected --type=app --select=projects --base=HEAD~1 | grep -q -E "api|web" && echo "Files changed, start new build" || exit 78

  - name: app
    image: docker:dind
    environment:
      PASSWORD:
        from_secret: registry_password
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5 # give docker enough time to start
      - echo $PASSWORD | docker login --username cfu288 --password-stdin
      - docker build -f Dockerfile -t cfu288/mere-medical .
      - docker push cfu288/mere-medical:latest
    # depends_on:
    #   - app-check-if-changed

  # - name: docs-check-if-changed
  #   image: node:16.14.0
  #   commands:
  #     - npm ci
  #     - npx nx print-affected --type=app --select=projects --base=HEAD~1
  #     # docs project is not detected by print affected yet
  #     - npx nx print-affected --type=app --select=projects --base=HEAD~1 | grep -q -E "docs" && echo "Files changed, start new build" || exit 78
  - name: docs
    image: docker:dind
    environment:
      PASSWORD:
        from_secret: registry_password
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5 # give docker enough time to start
      - echo $PASSWORD | docker login --username cfu288 --password-stdin
      - docker build -f Dockerfile-docs -t cfu288/mere-medical-docs .
      - docker push cfu288/mere-medical-docs:latest
    # depends_on:
    #   - docs-check-if-changed

  - name: parallelize builds
    image: docker:dind
    commands:
      - echo "Done"
    depends_on:
      - app
      - docs

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request
