kind: pipeline
name: default
type: docker

steps:
  - name: deploy
    image: codestation/drone-stack
    settings:
      host: ssh://cfu288@192.168.1.100
      stack_name: mari-medical
      compose: docker-compose.yml
      ssh_key:
        from_secret: ssh_key
