kind: pipeline
name: default
type: docker

steps:
  - name: app
    image: docker:dind
    environment:
      PASSWORD:
        from_secret: registry_password
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5 # give docker enough time to start
      - echo $PASSWORD | docker login --username cfu288 --password-stdin
      - docker build -f Dockerfile -t mari-medical .
      - docker tag mari-medical:latest mari-medical:latest
      - docker push mari-medical:latest

  - name: docs
    image: docker:dind
    environment:
      PASSWORD:
        from_secret: registry_password
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5 # give docker enough time to start
      - echo $PASSWORD | docker login --username cfu288 --password-stdin
      - docker build -f Dockerfile-docs -t mari-medical-docs .
      - docker tag mari-medical-docs:latest mari-medical-docs:latest
      - docker push mari-medical-docs:latest

  - name: parallelize builds
    image: docker:dind
    commands:
      - echo "Done"
    depends_on:
      - app
      - docs

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - main
