kind: pipeline
name: default
type: docker

steps:
  - name: deploy
    image: codestation/drone-stack
    settings:
      host: ssh://user@example.com
      stack_name: mystack
      compose: docker-compose.yml
      ssh_key:
        from_secret: ssh_key
