version: '3.9'

services:
  app:
    image: cfu288/mari-medical:latest
    ports:
      - '4200:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://app:4200/api/health']
    environment:
      - ONPATIENT_CLIENT_ID=${ONPATIENT_CLIENT_ID}
      - ONPATIENT_CLIENT_SECRET=${ONPATIENT_CLIENT_SECRET}
      - PUBLIC_URL=${PUBLIC_URL}
  docs:
    image: cfu288/mari-medical-docs:latest
    ports:
      - '4202:80'
