version: '3.9'

services:
  web:
    image: registry.mari.casa/mari-medical-web:latest
    ports:
      - '4200:80'
  api:
    image: registry.mari.casa/mari-medical-api:latest
    ports:
      - '4201:80'
    environment:
      - NX_ONPATIENT_CLIENT_SECRET=${ONPATIENT_CLIENT_SECRET}
      - NX_ONPATIENT_CLIENT_ID=${ONPATIENT_CLIENT_ID}
      - NX_ONPATIENT_REDIRECT=${ONPATIENT_REDIRECT}
      - NX_FRONTEND_APP_REDIRECT=${FRONTEND_APP_REDIRECT}
  # couchserver:
  #   image: couchdb
  #   restart: always
  #   ports:
  #     - '5984:5984'
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=YOURPASSWORD
  #   volumes:
  #     - /mnt/data/mari-medical/cdb:/opt/couchdb/data
