version: '3.9'

services:
  app:
    image: cfu288/mere-medical:beta
    ports:
      - '5200:80'
    healthcheck:
      test: ['CMD', 'node', '/app/healthcheck.js']
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 12 # How many times retries.
      start_period: 5s # Estimated time to boot.
    environment:
      - ONPATIENT_CLIENT_ID=${ONPATIENT_CLIENT_ID}
      - ONPATIENT_CLIENT_SECRET=${ONPATIENT_CLIENT_SECRET}
      - EPIC_CLIENT_ID=${EPIC_CLIENT_ID}
      - EPIC_SANDBOX_CLIENT_ID=${EPIC_SANDBOX_CLIENT_ID}
      - CERNER_CLIENT_ID=${CERNER_CLIENT_ID}
      - VERADIGM_CLIENT_ID=${VERADIGM_CLIENT_ID}
      - PUBLIC_URL=${PUBLIC_URL}
  docs:
    image: cfu288/mere-medical-docs:beta
    ports:
      - '5202:80'
  demo:
    image: cfu288/mere-medical:beta
    ports:
      - '5201:80'
    healthcheck:
      test: ['CMD', 'node', '/app/healthcheck.js']
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 12 # How many times retries.
      start_period: 5s # Estimated time to boot.
    stop_grace_period: 30s
    deploy:
      replicas: 1
      update_config:
        delay: 30s
        parallelism: 1
        order: start-first
        failure_action: rollback
    environment:
      - ONPATIENT_CLIENT_ID=${ONPATIENT_CLIENT_ID}
      - ONPATIENT_CLIENT_SECRET=${ONPATIENT_CLIENT_SECRET}
      - EPIC_CLIENT_ID=${EPIC_CLIENT_ID}
      - EPIC_SANDBOX_CLIENT_ID=${EPIC_SANDBOX_CLIENT_ID}
      - CERNER_CLIENT_ID=${CERNER_CLIENT_ID}
      - VERADIGM_CLIENT_ID=${VERADIGM_CLIENT_ID}
      - PUBLIC_URL=${PUBLIC_URL}
      - IS_DEMO=enabled
